import '@/lib/assets/styles/global.scss';
import { Wrapper } from '@/lib/components/layout/wrapper/wrapper';
import Header from '@/lib/components/ui/header/Header';

export const metadata = {
	title: 'Ookat',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<Wrapper>
					<Header />
					{children}
				</Wrapper>
			</body>
		</html>
	);
}
